import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // ✅ auto-generated by FlutterFire CLI
import 'screen/welcome_screen.dart';
import 'screen/login_screen.dart';
import 'screen/registration_screen.dart';
import 'screen/thankyou_screen.dart';
import 'screen/Homepage_contractor.dart';
import 'screen/wet_plant_hire_page.dart' as wet;
import 'screen/LumpSumContractorPage.dart';
import 'screen/lumpsumcontractorhire_listing.dart';
import 'screen/lumpsumcontractorhire_details.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform, // ✅ required if using firebase_options.dart
  );
  runApp(CostaCivilApp());
}

class CostaCivilApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Costa Civil',
      debugShowCheckedModeBanner: false,
      initialRoute: '/',
      routes: {
        '/': (context) => WelcomeScreen(),
        '/login': (context) => LoginScreen(),
        '/register': (context) => RegistrationScreen(),
        '/thankyou': (context) => ThankYouScreen(),
        '/Homepage_contractor': (context) => HomeScreen(),
        '/LumpSumContractorPage' : (context) => const LumpSumContractorPage(),
        '/wet_plant_hire': (context) => const wet.WetPlantHirePage(),

      },
    );
  }
}
