import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';

import 'firebase_options.dart'; // Auto-generated by FlutterFire CLI
import 'screen/welcome_screen.dart';
import 'screen/login_screen.dart';
import 'screen/registration_screen.dart';
import 'screen/thankyou_screen.dart';
import 'screen/Homepage_contractor.dart';
import 'screen/wet_plant_hire_page.dart' as wet;
import 'screen/LumpSumContractorPage.dart';
import 'screen/lumpsumcontractorhire_listing.dart';
import 'screen/lumpsumcontractorhire_details.dart';
import 'screen/dry_plant_hire_page.dart' as dry;
import 'screen/labourhirepage.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(CostaCivilApp());
}

class CostaCivilApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Costa Civil',
      debugShowCheckedModeBanner: false,
      home: AuthGate(), // This decides the initial screen
      routes: {
        '/login': (context) => LoginScreen(),
        '/register': (context) => RegistrationScreen(),
        '/thankyou': (context) => ThankYouScreen(),
        '/Homepage_contractor': (context) => HomeScreen(),
        '/LumpSumContractorPage': (context) => const LumpSumContractorPage(),
        '/wet_plant_hire': (context) => const wet.WetPlantHirePage(),
        '/dry_plant_hire': (context) => const dry.DryPlantHirePage(),
        '/labourhirepage': (context) => const LabourHirePage(),
      },
    );
  }
}

class AuthGate extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final user = FirebaseAuth.instance.currentUser;
    if (user != null) {
      return HomeScreen(); // user is logged in
    } else {
      return WelcomeScreen(); // show welcome/login flow
    }
  }
}
